name: 'Build and Deploy'
on: ['push']
jobs:
  build-and-deploy:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout 🛎️'
        uses: 'actions/checkout@v2.3.1'

      - name: 'Install and Build 🔧'
        run: |
          yarn
          yarn build
          yarn export
          touch out/.nojekyll

      - name: 'Deploy 🚀'
        uses: 'JamesIves/github-pages-deploy-action@4.1.7'
        with:
          branch: 'gh-pages'
          folder: 'out'
